<?php
/**
 * @var $this \App\Blocks\View
 */
?>

<header>
    <div class="container">
        <div class="flex">
            <a class="layout-header__authentication-link" href="/">
                <div class="logo">
                    <img src="/assets/icons/aclogo.png" alt="logo" class="logo_img">
                </div>
            </a>
            <a class="layout-header__authentication-link" href="/courses">
                <div class="courses">
                    <img src="/assets/icons/acallcourses.png" alt="courses" class="courses_img">
                    <div class="text_header">Все курсы</div>
                </div>
            </a>
            <a class="layout-header__authentication-link" href="/events">
                <div class="text_header">Мероприятия</div>
            </a>
            <div class="text_header">Базы знаний</div>
            <div class="text_header">Карьера</div>
            <div class="city">
                <img src="/assets/icons/accity.png" alt="icon of city" class="city_img">
                <div id="line_city" class="text_header">Нижний Новгород</div>
                <img src="/assets/icons/down.png" alt="down" class="down_img">
            </div>
            <div class="text_header">8 800 950-33-98</div>
            <a class="layout-header__authentication-link" href="/login">
                <div class="signin">
                    <img src="/assets/icons/acsignin.png" alt="icon of sign in" class="signin_img">
                    <div class="text_header">
                        <?php if ($this->user): ?>
                            <div class="text_header">Выйти</div>
                        <?php else: ?>
                            <div class="text_header">Войти</div>
                        <?php endif; ?>
                    </div>
                </div>
            </a>
        </div>
    </div>
</header>

<div class="girl"></div>

<section class="futureaca">
    <div class="container">
        <div class="futureaca_text">
            <h1>Образовательная платформа</h1>
            <h1>ХОД Future Academy</h1>
            <h2>Актуальные знания для новчиков и профессионалов</h2>
        </div>
    </div>
</section>

<section class="main">
    <div class="container">
        <div class="owl_speak">
            <div class="owl_text">
                <div class="text1">Кем вы хотите стать?</div>
                <div class="text2">Пора найти себя и выбрать подходящий курс :)</div>
                <div class="text2">Удачи!</div>
            </div>
            <img src="/assets/img/union.png" alt="dialog icon" class="dialog_icon">
            <img src="/assets/img/owl.png" alt="owl" class="owl">
            <img src="/assets/img/union_mob.png" alt="dialog icon" class="dialog_icon_mob">
            <img src="/assets/img/owl_mob.png" alt="owl" class="owl_mob">
        </div>

        <div class="audience_choose">
            <div class="audience">
                <div id="first_box" class="audience_box">
                    <img src="/assets/icons/children.png" alt="children icon" class="img_audience">
                    <div class="audience_text">
                        <div class="name">Дети</div>
                        <div class="age">8 — 14 лет</div>
                    </div>
                </div>
                <div class="audience_box">
                    <img src="/assets/icons/teenagers.png" alt="teenagers icon" class="img_audience">
                    <div class="audience_text">
                        <div class="name">Подростки</div>
                        <div class="age">14 — 18 лет</div>
                    </div>
                </div>
                <div id="third_box" class="audience_box">
                    <img src="/assets/icons/family.png" alt="adults icon" class="img_audience">
                    <div class="audience_text">
                        <div class="name">Взрослые</div>
                        <div class="age">18 — ∞</div>
                    </div>
                </div>
            </div>
            <div class="course">
                <button class="course_box">Робототехника</button>
                <button class="course_box">Создание игр</button>
                <button class="course_box" id="web">Web-разработка</button>
                <button class="course_box" id="multi">Мультимедиа</button>
                <?php foreach ($this->getAll() as $course): ?>
                    <?php if ($course): ?>
                        <button class="course_box" id="current_course" onclick="location.href = '/courses/course?id=<?php echo $course->getId();?>'">
                            <?php echo $course->getName();?>
                        </button>
                    <?php endif; ?>
                <?php endforeach; ?>
                <button class="course_box" id="model">3D-модерирование и дизайн</button>
                <button class="course_box" id="english">Английский язык</button>
                <button class="course_box" id="bloging">Блогинг</button>
                <button class="course_box" id="soft_skills">Soft skills</button>
            </div>
        </div>

        <div class="boy_img" >
            <img src="/assets/img/boy.png" alt="boy" class="boy">
            <img src="/assets/img/play.png" alt="play" class="button_play">
            <img src="/assets/img/play_mob.png" alt="play" class="button_play_mob">
        </div>
        <div class="some_text">Актуальные знания от признанных экспертов рынка для новичков и практикующих специалистов.</div>
        <div class="numbers_text">
            <div class="numbers_box" id="numbers_box1">
                <div class="numbers">600</div>
                <div class="text">Курсов</div>
            </div>
            <div class="numbers_box">
                <div class="numbers">82</div>
                <div class="text">Ведущих преподавателей</div>
            </div>
            <div class="numbers_box">
                <div class="numbers">14 795</div>
                <div class="text">Выпускников</div>
            </div>
        </div>

        <div class="cards">
            <div class="day_open_door">
                <div class="day">
                    <img src="/assets/img/25.png" alt="data"  class="day_number">
                    <img src="/assets/img/25_mob.png" alt="data"  class="day_number_mob">
                    <img src="/assets/img/november.png" alt="month" class="month">
                    <img src="/assets/img/november_mob.png" alt="month" class="month_mob">
                </div>
                <div class="name_cards_mob">День открытых дверей</div>
                <div class="day_text">
                    <div class="name_cards">День открытых дверей</div>
                    <div class="text_cards">Приглашаем всех желающих на бесплатную экскурсию в мир востребованных профессий и полезных навыков</div>
                </div>
                <div class="sign_up">
                    <div class="sign_up_text">Записаться</div>
                    <img src="/assets/img/arrow.png" alt="arrow" class="arrow">
                </div>
            </div>

            <div class="training_programs">
                <img src="/assets/icons/monitor.png" alt="monitor" class="monitor">
                <div class="name_cards">Программы обучения</div>
                <div class="text_cards">В списке наших курсов вы сможете найти профессию и занятие по душе, изучить новое и получить практические знания, которые помогут получить работу мечты.</div>
                <div class="sign_up">
                    <div class="sign_up_text">Подробнее</div>
                    <img src="/assets/img/arrow.png" alt="arrow" class="arrow">
                </div>
            </div>

            <div class="block_for_flex">
                <div class="academy_news">
                    <img src="/assets/icons/newspaper.png" alt="newspaper" class="newspaper">
                    <div class="name_cards">Новости Академии</div>
                </div>

                <div class="world_it">
                    <img src="/assets/icons/diagram.png" alt="diagram" class="diagram">
                    <div class="name_cards">Мир IT</div>
                </div>

                <div class="try">
                    <img src="/assets/icons/symbols_mob.png" alt="symbols" class="symbols_mob">
                    <img src="/assets/icons/symbols.png" alt="symbols" class="symbols">

                    <div class="name_cards_mob">Попробуй!</div>
                    <div class="day_text">
                        <div class="name_cards">Попробуй!</div>
                        <div class="text_cards">Пройдите тест и узнайте свои способности в сфере информационных технологий</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="reviews">
        <div class="container">
            <div class="rewiws_title">Отзывы наших студентов</div>
            <div class="students">
                <div class="student">
                    <img src="/assets/img/photo.png" alt="photo" class="photo">
                    <div class="name_role">
                        <div class="name_students">Имя Фамилия</div>
                        <div class="role">Студент курса «WEB-разработчик»</div>
                    </div>
                    <div class="text_rewiew">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat nisl at augue dapibus, id tristique lorem placerat. Curabitur pellentesque est bibendum urna facilisis varius. In hac habitasse platea dictumst. In ut dui sodales, scelerisque eros non, ultrices magna. </div>
                    <div class="estimation">
                        <img src="/assets/icons/star.png" alt="star" class="star">
                        <div class="number_estimation">4,87 / 5</div>
                    </div>
                </div>
                <div class="student">
                    <img src="/assets/img/photo.png" alt="photo" class="photo">
                    <div class="name_role">
                        <div class="name_students">Имя Фамилия</div>
                        <div class="role">Студент курса «WEB-разработчик»</div>
                    </div>
                    <div class="text_rewiew">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat nisl at augue dapibus, id tristique lorem placerat. Curabitur pellentesque est bibendum urna facilisis varius. In hac habitasse platea dictumst. In ut dui sodales, scelerisque eros non, ultrices magna. </div>
                    <div class="estimation">
                        <img src="/assets/icons/star.png" alt="star" class="star">
                        <div class="number_estimation">4,87 / 5</div>
                    </div>
                </div>
            </div>
            <div class="line"></div>
            <div class="colour_line"></div>
        </div>
    </div>

    <div class="container">
        <div class="welcome">Добро пожаловать в Академию будущего ХОД</div>
        <div class="coins">
            <div class="coins_box">
                <img src="/assets/icons/advanced.png" alt="advanced">
                <div class="coins_text" id="first_coins_box">Передовой подход к образовательному процессу</div>
            </div>
            <div class="coins_box">
                <img src="/assets/icons/book.png" alt="book">
                <div class="coins_text" id="second_coins_box">Непрерывное усовершенствование и пополнение базы курсов</div>
            </div>
            <div class="coins_box">
                <img src="/assets/icons/teachers.png" alt="teachers">
                <div class="coins_text" id="third_coins_box">Только практикующие преподаватели</div>
            </div>
            <div class="coins_box">
                <img src="/assets/icons/convoy.png" alt="convoy">
                <div class="coins_text" id="four_coins_box">Сопровождение на всех этапах. От начала обучения до трудоустройства</div>
            </div>
        </div>

        <div class="help_with_choice">
            <div class="owl_speak_in_footer">
                <div class="owl_text_in_footer">
                    <div class="text1_in_footer">Помочь с выбором?</div>
                    <div class="text2_in_footer">Оставьте заявку и наши специалисты свяжутся с вами, ответят на все вопросы и подберут подходящий вариант обучения.</div>
                </div>

                <img src="/assets/img/union_footer.png" alt="dialog icon" class="dialog_icon_in_footer">
                <img src="/assets/img/owl_footer.png" alt="owl" class="owl_in_footer">
                <img src="/assets/img/owl_footer_mob.png" alt="owl" class="owl_in_footer_mob">
                <img src="/assets/img/union_footer_mob.png" alt="dialog icon" class="dialog_icon_in_footer_mob">
            </div>

            <div class="contact_form">
                <div class="input">
                    <div class="name_input">Ваше имя</div>
                    <div class="phone">Ваш телефон</div>
                    <div class="email">Ваш e-mail</div>
                    <div class="policy">Нажимая на кнопку, я соглашаюсь на обработку персональных данных и с правилами пользования Платформой</div>
                    <button class="send">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</section>